apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPO_URL
    targetRevision: TARGET_REVISION
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: obsapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
